In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/ankushsharma0904/Career-guidance-project/main/Data/dataset9000.csv')

In [ ]:
dataset.dropna(how ='all', inplace = True)

In [ ]:
data = pd.get_dummies(dataset, columns=['Database Fundamentals', 'Computer Architecture', 'Distributed Computing Systems',
                                        'Cyber Security', 'Networking','Software Development', 'Programming Skills',
                                        'Project Management', 'Computer Forensics Fundamentals', 'Technical Communication', 
                                        'AI ML', 'Software Engineering', 'Business Analysis', 'Communication skills',
                                        'Data Science', 'Troubleshooting skills', 'Graphics Designing' ])

In [ ]:
X = data.drop('Role', axis=1)
Y = data['Role']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
# Splitting dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 1/3, random_state = 1)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
scores = {}
knn = KNeighborsClassifier(n_neighbors=5)


In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
knn.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
knn.effective_metric_

'euclidean'

In [ ]:
knn.effective_metric_params_

{}

In [ ]:
knn.n_features_in_

119

In [ ]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
knn.kneighbors()

(array([[1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        ...,
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356]]),
 array([[5886, 2275, 2611, 2659, 4476],
        [4514, 4524, 1887, 5505, 4040],
        [5044, 2368,  443, 3894, 5688],
        ...,
        [2525, 6063,  619, 4551, 3733],
        [5942, 5910, 6038, 2904, 1948],
        [5615, 1521, 3899, 1995, 2495]]))

In [1]:
plt.knn.kneighbors_graph()
plt.show()

NameError: ignored